export const fruitUrls = {
    "Apple": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Apple-png.png",
    "Annona": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Annona-jpg.jpg",
    "Apricot": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Apricot-webp.webp",
    "Avocado": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Avocado-jpg.jpg",
    "Banana": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Banana-webp.webp",
    "Blackberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Blackberry-jpg.jpg",
    "Blueberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Blueberry-png.png?t=2024-12-29T20%3A34%3A57.096Z",
    "Ceylon Gooseberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Ceylon%20Gooseberry-jpg.jpg",
    "Cherry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Cherry-png.png",
    "Cranberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Cranberry-jpg.jpg",
    "Dragonfruit": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Dragonfruit-png.png",
    "Durian": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Durian-png.png",
    "Feijoa": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Feijoa-jpg.jpg",
    "Fig": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Fig-webp.webp",
    "Gooseberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Gooseberry-jpg.jpg",
    "Grape": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Grape-jpg.jpg",
    "GreenApple": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/GreenApple-jpg.jpg",
    "Guava": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Guava-jpg.jpg",
    "Hazelnut": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Hazelnut-png.png",
    "Horned Melon": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Horned%20Melon-jpg.jpg",
    "Jackfruit": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Jackfruit-jpg.jpg",
    "Japanese Persimmon": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Japanese%20Persimmon-jpg.jpg",
    "Kiwifruit": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Kiwifruit-jpg.jpg",
    "Kiwi": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Kiwi-jpg.jpg",
    "Lemon": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Lemon-png.png",
    "Lime": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Lime-jpg.jpg",
    "Lingonberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Lingonberry-png.png",
    "Lychee": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Lychee-jpg.jpg",
    "Mango": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Mango-jpg.jpg",
    "Mangosteen": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Mangosteen-jpg.jpg",
    "Melon": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Melon-jpg.jpg",
    "Morus": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Morus-png.png",
    "Orange": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Orange-jpg.jpg",
    "Papaya": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Papaya-jpg.jpg",
    "Peach": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Peach-jpg.jpg",
    "Passionfruit": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Passionfruit-jpg.jpg",
    "Pear": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Pear-jpg.jpg",
    "Persimmon": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/persimmon-jpg.jpg",
    "Pineapple": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Pineapple-jpg.jpg",
    "Pitahaya": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Pitahaya-webp.webp",
    "Plum": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Plum-jpg.jpg",
    "Pomegranate": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Pomegranate-jpg.jpg",
    "Pomelo": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Pomelo-png.png",
    "Pumpkin": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Pumpkin-webp.webp",
    "Raspberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Raspberry-png.png",
    "Strawberry": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Strawberry-webp.webp",
    "Tangerine": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Tangerine-png.png",
    "Tomato": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Tomato-jpg.jpg",
    "Watermelon": "https://pqhdnqsudvqgoivgnlvy.supabase.co/storage/v1/object/public/fruits/Watermelon-webp.webp",
};
